### PR TITLE
Use git "commondir" for reference lookups

### LINKED ISSUE #553: WorkTree With managed Git
When runing `nbgv get-version` (with nbgv version v3.4.161-alpha+a44c1fae2a) in my git worktree i get the following error

    ERROR: The commit 0000000000000000000000000000000000000000 was not found in this repository.

When falling back to LibGit2 it works as expected

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #553

### CODE REVIEW

**Comment by AArnott** [comment]
@qmfrederik Can you please review?

File: src/NerdBank.GitVersioning/ManagedGit/GitRepository.cs [hunk 1]
```diff
@@ -128,13 +128,13 @@ public static GitRepository Create(string workingDirectory, string gitDirectory,
         public GitRepository(string workingDirectory, string gitDirectory, string commonDirectory, string objectDirectory)
         {
             this.WorkingDirectory = workingDirectory ?? throw new ArgumentNullException(nameof(workingDirectory));
-            this.GitDirectory = gitDirectory ?? throw new ArgumentNullException(nameof(gitDirectory));
+            this.GitHeadDirectory = gitDirectory ?? throw new ArgumentNullException(nameof(gitDirectory));
```
Comment (qmfrederik) [inline src/NerdBank.GitVersioning/ManagedGit/GitRepository.cs:131]: I tried to keep the variable names consistent with the names used by Git. For example, the Git documentation references this directory as `$GIT_DIR` (see https://git-scm.com/docs/gitrepository-layout). So it may make sense to keep `GitDirectory` as the name

At the same time, I have to admit I also get lost in those names from time to time, and `GitHeadDirectory` does make the intent clear.

If you change the name to `GitHeadDirectory`, then these remarks:
- Perhaps the `Git` prefix (other variables are named `CommonDirectory` and `ObjectDirectory`, for example)
- Update the name of the `gitDirectory` argument in the constructor (and other methods that call the constructor).

**Comment by qmfrederik** [comment]
Thanks, @AArnott. I have a minor remark regarding the variable names - up to you.

File: src/NerdBank.GitVersioning/ManagedGit/GitRepository.cs (hunk 1 above)
Comment (AArnott) [reply src/NerdBank.GitVersioning/ManagedGit/GitRepository.cs:131]: Ya, I am conflicted on it too. But the desire to avoid bugs in this area won out for me. But the additional name changes you suggest makes sense. I'll apply those.

Comment (AArnott) [reply src/NerdBank.GitVersioning/ManagedGit/GitRepository.cs:131]: Interesting. In reading the doc you linked to, I guess more than HEAD can arrear under this directory and mentions "a few known exceptions" that it unfortunately does not list. So I guess I'll leave the naming as it was but do my best to prominently comment to avoid bugs.
